title: "Viroit"
description: "全角英数や半角カナが判別しやすい、文字間隔調整機能付き等幅フォント"

url: "https://omonomo.github.io"
baseurl: "/Viroit"

plugins:
  - jekyll-readme-index
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: "/images/social-preview.png"
