# ターミナルから直接実行する場合
# docker compose run --rm font ./run_ff_ttx.sh -F [オプション]
#
# コンテナに入ってから実行する場合
# docker compose run -it --rm font
# exit で抜けます

services:
  font:
    build: .
    volumes:
      - ./build:/app/build
      - karningcache:/app/karningSettings
      - fontcache:/app/nopatchFonts

volumes:
  karningcache:
  fontcache:
