# ターミナルから直接実行する場合
# docker compose run --rm font ./run_ff_ttx.sh -F [オプション]
#
# コンテナに入ってから実行する場合
# docker compose run -it --rm font
# exit で抜けます
#
# ソースコードに変更があった場合、先に
# docker compose build
# を実行

services:
  font:
    build: .
    volumes:
      - ./build:/app/build
      - karningcaches:/app/karningSettings
      - fontcaches:/app/nopatchFonts

volumes:
  karningcaches:
  fontcaches:
